### ISSUE TITLE
Add Pete's mobile search toggle feature to masthead

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/brand-patterns#31]

**Comment by adamjohnson** [comment]
Looks like you're referencing some images with `http` instead of `https`. 

Also, is it possible to lower the specificity of some of these selectors? For example: `#searcher.inactive-search` ? Maybe that could be a single class, or, a combination selector like `.searcher.inactive-search`?

https://github.com/wvuweb/brand-patterns/commit/b901cc251015572b466c8de465ee90ec0d381d08#diff-bcb92fb419ad3d6fe43c728ba73a28baR38

Here's why not to use ID's:

http://cssguidelin.es/#ids-in-css

b901cc251015572b466c8de465ee90ec0d381d08 is related to this issue.

**Comment by zeroedin** [comment]
+1 to @adamjohnson response
